language: node_js

sudo: false

node_js:
- 6

before_deploy:
  - npm i -g serverless

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - serverless create_domain
      - serverless deploy --stage staging
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      - serverless create_domain
      - serverless deploy --stage prod
    on:
      branch: production
