service: tim-bot

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs6.10
  stage: ${file(.env.yml):DEPLOY_ALIAS, "dev"}
  environment: ${file(.env.yml)}

functions:
  fbVerify:
    handler: entrypoint/fb.verify
    events:
      - http:
          path: fb
          method: get
  fbMessage:
    handler: entrypoint/fb.message
    events:
      - http:
          path: fb
          method: post

custom:
  customDomain:
    domainName: "${self:provider.stage}.bot.tim.app.wdr.cloud"
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-offline
  - serverless-domain-manager
