service: tim-bot

provider:
  name: aws
  region: ${file(config.yml):region}
  runtime: nodejs6.10
  stage: ${file(config/env.js):stage}
  environment: ${file(config/env.js):env}

functions:
  fbVerify:
    handler: entrypoint/fb.verify
    events:
      - http:
          path: fb
          method: get
  fbMessage:
    handler: entrypoint/fb.message
    events:
      - http:
          path: fb
          method: post
  cronPush:
    handler: entrypoint/fb.push
    timeout: 30
    events:
      - http:
          path: push
          method: get
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_morning
          rate: cron(30 6 * * ? *)  # UTC+1 (No DST)
          input:
            timing: morning
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_morning_dst
          rate: cron(30 5 * * ? *)  # UTC+2 (DST)
          input:
            timing: morning
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_evening
          rate: cron(30 17 * * ? *)  # UTC+1 (No DST)
          input:
            timing: evening
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_evening_dst
          rate: cron(30 16 * * ? *)  # UTC+2 (DST)
          input:
            timing: evening

custom:
  customDomain:
    domainName: "${self:provider.stage}.${file(config.yml):domain_base}"
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${file(config/env.js):enableDomain}
  scripts:
    hooks:
      'package:initialize': npm run lint

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-scripts
