service: tim-bot

provider:
  name: aws
  region: ${file(config.yml):region}
  runtime: nodejs6.10
  stage: ${file(config/env.js):stage}
  environment: ${file(config/env.js):env}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-${self:provider.stage}-*"

functions:
  fbVerify:
    handler: entrypoint/fb.verify
    events:
      - http:
          path: fb
          method: get
  fbMessage:
    handler: entrypoint/fb.message
    timeout: 15
    events:
      - http:
          path: fb
          method: post
  fbAttachment:
    handler: entrypoint/fb.attachment
    timeout: 30
    events:
      - http:
          path: attachment
          method: post
  cronPush:
    handler: entrypoint/fb.push
    timeout: 30
    events:
      - http:
          path: push
          method: get
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_morning_2
          rate: cron(30 6 ? * MON-FRI *)  # UTC+1 (No DST)
          input:
            timing: morning
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_morning_dst_2
          rate: cron(30 5 ? * MON-FRI *)  # UTC+2 (DST)
          input:
            timing: morning
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_morning_weekend_2
          rate: cron(0 8 ? * SAT,SUN *)  # UTC+1 (No DST)
          input:
            timing: morning
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_morning_weekend_dst_2
          rate: cron(0 7 ? * SAT,SUN *)  # UTC+2 (DST)
          input:
            timing: morning
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_evening_2
          rate: cron(30 17 * * ? *)  # UTC+1 (No DST)
          input:
            timing: evening
      - schedule:
          name: ${self:service}-${self:provider.stage}-push_evening_dst_2
          rate: cron(30 16 * * ? *)  # UTC+2 (DST)
          input:
            timing: evening

custom:
  customDomain:
    domainName: "${self:provider.stage}.${file(config.yml):domain_base}"
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${file(config/env.js):enableDomain}
  scripts:
    hooks:
      'package:initialize': npm run lint

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-scripts

resources:
  Resources: ${file(config/env.js):resources}
