service: tim-bot

provider:
  name: aws
  region: ${file(config.yml):region}
  runtime: nodejs6.10
  stage: ${file(.env.yml):DEPLOY_ALIAS, "dev"}
  environment: ${file(.env.yml)}

functions:
  fbVerify:
    handler: entrypoint/fb.verify
    events:
      - http:
          path: fb
          method: get
  fbMessage:
    handler: entrypoint/fb.message
    events:
      - http:
          path: fb
          method: post

custom:
  customDomain:
    domainName: "${self:provider.stage}.${file(config.yml):domain_base}"
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-offline
  - serverless-domain-manager
