service: tim-bot 

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs6.10
  environment: ${file(.env.yml)}

functions:
  fbVerify:
    handler: entrypoint/fb.verify
    events: 
      - http: 
          path: fb
          method: get
  fbMessage:
    handler: entrypoint/fb.message
    events:
      - http:
          path: fb
          method: post

plugins:
  - serverless-offline
